/**
 *
 * CSCI 401 Ian Jeff Rebecca Fall 2016
 */

public class ChooseUser extends javax.swing.JFrame {

    /**
     * Creates new form ChooseUser
     */
    public ChooseUser() {
        initComponents();
        EditPrices test = new EditPrices();
        submit.setVisible(false);
        incorrect.setVisible(false);
        pinbox.setVisible(false);
        testField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        testField = new javax.swing.JTextField();
        submit = new javax.swing.JLabel();
        incorrect = new javax.swing.JLabel();
        pinbox = new javax.swing.JLabel();
        Manager = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Customer = new javax.swing.JLabel();
        Kitchen = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testField.setBorder(null);
        jPanel1.add(testField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 40));

        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 100, 30));

        incorrect.setForeground(new java.awt.Color(255, 255, 255));
        incorrect.setText("Incorrect Pin: Please Try Again");
        jPanel1.add(incorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 260, 40));

        pinbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpin.png"))); // NOI18N
        jPanel1.add(pinbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 400, 290));

        Manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManagerMouseClicked(evt);
            }
        });
        jPanel1.add(Manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 146, 200, 220));

        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 50, 60));

        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
        });
        jPanel1.add(Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 190, 200));

        Kitchen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KitchenMouseClicked(evt);
            }
        });
        jPanel1.add(Kitchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, 200));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/choosenew.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 850, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Goes to pay bill
    */
    private void KitchenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KitchenMouseClicked

    }//GEN-LAST:event_KitchenMouseClicked

    /**
    * Goes to customer mode
    */
    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_CustomerMouseClicked

    /**
    * Displays the enter pin box 
    */
    private void ManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerMouseClicked
        pinbox.setVisible(true);
        submit.setVisible(true);
        testField.setVisible(true);
    }//GEN-LAST:event_ManagerMouseClicked

    /**
    * Exits program
    */
    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    /**
    * If the pin is correct, goes to manager mode. If incorrect notifies user
    */
    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        if(testField.getText().equals("1111")){
            this.setVisible(false);
            new ManagerMode().setVisible(true);
        }
        else{
            incorrect.setVisible(true);
        }
            
    }//GEN-LAST:event_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customer;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Kitchen;
    private javax.swing.JLabel Manager;
    private javax.swing.JLabel background;
    private javax.swing.JLabel incorrect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pinbox;
    private javax.swing.JLabel submit;
    private javax.swing.JTextField testField;
    // End of variables declaration//GEN-END:variables
}
