/**
 *
 * CSCI 401 Ian Jeff Rebecca Fall 2016
 */

import javax.swing.JComboBox;
import java.text.DecimalFormat;


public class EditPrices extends javax.swing.JFrame {

    private MenuItem nachos;
    private MenuItem onionRings;
    private MenuItem fries;
    private MenuItem mozzSticks;
    private MenuItem potatoSkins;
    private MenuItem sliders;
    private MenuItem chickenWings;
    private MenuItem chickenTenders;
    private MenuItem cheeseFries;
    private MenuItem sideGardenSal;
    private MenuItem sideCaesarSal;
    private MenuItem chipsSalsa;
    private MenuItem friedRavioli;
    private MenuItem jalapenoPoppers;
    private MenuItem calamari;
    private MenuItem soupOfTheDay;
    private MenuItem strawberryDaiquiri;
    private MenuItem pinaColada;
    private MenuItem whiteZin;
    private MenuItem cabernet;
    private MenuItem pinotGrigio;
    private MenuItem margarita;
    private MenuItem yuengling;
    private MenuItem budLight;
    private MenuItem[] menuChoices = new MenuItem[24];
    private JComboBox[] coupons = new JComboBox[24];
    
    public static MenuItem[] setMenu = new MenuItem[24];
    public static int count = 0;
    
    private DecimalFormat df = new DecimalFormat("0.00");
    /**
     * Creates new form EditPrices
     */
    public EditPrices() {
        initComponents();
        populateMenu();
        setCheckBoxes();
        makeComboArray();
        setDefaultPrices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        price2 = new javax.swing.JTextField();
        price3 = new javax.swing.JTextField();
        price4 = new javax.swing.JTextField();
        price5 = new javax.swing.JTextField();
        price6 = new javax.swing.JTextField();
        price7 = new javax.swing.JTextField();
        price8 = new javax.swing.JTextField();
        price13 = new javax.swing.JTextField();
        price14 = new javax.swing.JTextField();
        price15 = new javax.swing.JTextField();
        price16 = new javax.swing.JTextField();
        price17 = new javax.swing.JTextField();
        price18 = new javax.swing.JTextField();
        price19 = new javax.swing.JTextField();
        price20 = new javax.swing.JTextField();
        item1 = new javax.swing.JCheckBox();
        coupon1 = new javax.swing.JComboBox();
        item15 = new javax.swing.JCheckBox();
        item13 = new javax.swing.JCheckBox();
        item14 = new javax.swing.JCheckBox();
        item20 = new javax.swing.JCheckBox();
        item19 = new javax.swing.JCheckBox();
        item16 = new javax.swing.JCheckBox();
        item4 = new javax.swing.JCheckBox();
        item18 = new javax.swing.JCheckBox();
        item3 = new javax.swing.JCheckBox();
        item2 = new javax.swing.JCheckBox();
        item5 = new javax.swing.JCheckBox();
        item17 = new javax.swing.JCheckBox();
        item6 = new javax.swing.JCheckBox();
        item7 = new javax.swing.JCheckBox();
        item8 = new javax.swing.JCheckBox();
        coupon13 = new javax.swing.JComboBox();
        coupon14 = new javax.swing.JComboBox();
        coupon18 = new javax.swing.JComboBox();
        coupon15 = new javax.swing.JComboBox();
        coupon19 = new javax.swing.JComboBox();
        coupon16 = new javax.swing.JComboBox();
        coupon17 = new javax.swing.JComboBox();
        coupon20 = new javax.swing.JComboBox();
        coupon2 = new javax.swing.JComboBox();
        coupon5 = new javax.swing.JComboBox();
        coupon3 = new javax.swing.JComboBox();
        coupon4 = new javax.swing.JComboBox();
        coupon8 = new javax.swing.JComboBox();
        coupon7 = new javax.swing.JComboBox();
        coupon6 = new javax.swing.JComboBox();
        item9 = new javax.swing.JCheckBox();
        item10 = new javax.swing.JCheckBox();
        item11 = new javax.swing.JCheckBox();
        item12 = new javax.swing.JCheckBox();
        price9 = new javax.swing.JTextField();
        price10 = new javax.swing.JTextField();
        price11 = new javax.swing.JTextField();
        price12 = new javax.swing.JTextField();
        coupon9 = new javax.swing.JComboBox();
        coupon10 = new javax.swing.JComboBox();
        coupon11 = new javax.swing.JComboBox();
        coupon12 = new javax.swing.JComboBox();
        item21 = new javax.swing.JCheckBox();
        item22 = new javax.swing.JCheckBox();
        item23 = new javax.swing.JCheckBox();
        item24 = new javax.swing.JCheckBox();
        price21 = new javax.swing.JTextField();
        price23 = new javax.swing.JTextField();
        price22 = new javax.swing.JTextField();
        price24 = new javax.swing.JTextField();
        coupon23 = new javax.swing.JComboBox();
        coupon22 = new javax.swing.JComboBox();
        coupon21 = new javax.swing.JComboBox();
        coupon24 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Menu/Prices/Promos");

        price1.setText("0.00");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        price2.setText("0.00");

        price3.setText("0.00");

        price4.setText("0.00");

        price5.setText("0.00");

        price6.setText("0.00");

        price7.setText("0.00");

        price8.setText("0.00");

        price13.setText("0.00");

        price14.setText("0.00");

        price15.setText("0.00");

        price16.setText("0.00");

        price17.setText("0.00");

        price18.setText("0.00");

        price19.setText("0.00");

        price20.setText("0.00");

        item1.setForeground(new java.awt.Color(240, 240, 240));
        item1.setText("Menu Item");
        item1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });

        coupon1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        item15.setForeground(new java.awt.Color(240, 240, 240));
        item15.setText("Menu Item");
        item15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item13.setForeground(new java.awt.Color(240, 240, 240));
        item13.setText("Menu Item");
        item13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item14.setForeground(new java.awt.Color(240, 240, 240));
        item14.setText("Menu Item");
        item14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item20.setForeground(new java.awt.Color(240, 240, 240));
        item20.setText("Menu Item");
        item20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item19.setForeground(new java.awt.Color(240, 240, 240));
        item19.setText("Menu Item");
        item19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item16.setForeground(new java.awt.Color(240, 240, 240));
        item16.setText("Menu Item");
        item16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item4.setForeground(new java.awt.Color(240, 240, 240));
        item4.setText("Menu Item");
        item4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item18.setForeground(new java.awt.Color(240, 240, 240));
        item18.setText("Menu Item");
        item18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item3.setForeground(new java.awt.Color(240, 240, 240));
        item3.setText("Menu Item");
        item3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item2.setForeground(new java.awt.Color(240, 240, 240));
        item2.setText("Menu Item");
        item2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item5.setForeground(new java.awt.Color(240, 240, 240));
        item5.setText("Menu Item");
        item5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item17.setForeground(new java.awt.Color(240, 240, 240));
        item17.setText("Menu Item");
        item17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item6.setForeground(new java.awt.Color(240, 240, 240));
        item6.setText("Menu Item");
        item6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item7.setForeground(new java.awt.Color(240, 240, 240));
        item7.setText("Menu Item");
        item7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item8.setForeground(new java.awt.Color(240, 240, 240));
        item8.setText("Menu Item");
        item8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        coupon13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        item9.setForeground(new java.awt.Color(240, 240, 240));
        item9.setText("Strawberry Daiquiri");
        item9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        item9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item9ActionPerformed(evt);
            }
        });

        item10.setForeground(new java.awt.Color(240, 240, 240));
        item10.setText("Menu Item");
        item10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item11.setForeground(new java.awt.Color(240, 240, 240));
        item11.setText("Menu Item");
        item11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item12.setForeground(new java.awt.Color(240, 240, 240));
        item12.setText("Menu Item");
        item12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        price9.setText("0.00");

        price10.setText("0.00");

        price11.setText("0.00");

        price12.setText("0.00");

        coupon9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        item21.setForeground(new java.awt.Color(240, 240, 240));
        item21.setText("Menu Item");
        item21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item22.setForeground(new java.awt.Color(240, 240, 240));
        item22.setText("Menu Item");
        item22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item22.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item23.setForeground(new java.awt.Color(240, 240, 240));
        item23.setText("Menu Item");
        item23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item23.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        item24.setForeground(new java.awt.Color(240, 240, 240));
        item24.setText("Menu Item");
        item24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        item24.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        price21.setText("0.00");

        price23.setText("0.00");

        price22.setText("0.00");

        price24.setText("0.00");

        coupon23.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon22.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon21.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        coupon24.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Coupon", "10% off", "20% off", "50% off" }));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Price");

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(item2)
                                    .addComponent(item1)
                                    .addComponent(item3)
                                    .addComponent(item4)
                                    .addComponent(item5))
                                .addGap(2, 2, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(item7)
                                    .addComponent(item8)
                                    .addComponent(item6)
                                    .addComponent(item10)
                                    .addComponent(item11)
                                    .addComponent(item9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(item12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                .addComponent(item13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coupon12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item24)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(price13, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(price14)
                            .addComponent(price15)
                            .addComponent(price16)
                            .addComponent(price17)
                            .addComponent(price18)
                            .addComponent(price19)
                            .addComponent(price20)
                            .addComponent(price24)
                            .addComponent(price23)
                            .addComponent(price22)
                            .addComponent(price21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coupon13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(coupon20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(coupon24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coupon23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coupon22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coupon21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1)
                    .addComponent(coupon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item13)
                    .addComponent(coupon13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item14)
                    .addComponent(item2)
                    .addComponent(coupon14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item15)
                    .addComponent(item3)
                    .addComponent(coupon15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item16)
                    .addComponent(item4)
                    .addComponent(coupon16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item17)
                    .addComponent(item5)
                    .addComponent(coupon17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item18)
                    .addComponent(item6)
                    .addComponent(coupon18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item19)
                    .addComponent(item7)
                    .addComponent(coupon19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item20)
                    .addComponent(item8)
                    .addComponent(coupon20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coupon9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item9)
                    .addComponent(item21)
                    .addComponent(price21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coupon10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item10)
                    .addComponent(item22)
                    .addComponent(price22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coupon11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item11)
                    .addComponent(item23)
                    .addComponent(price23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coupon12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item12)
                    .addComponent(item24)
                    .addComponent(price24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Goes to manager mode
     * 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new ManagerMode().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ActionPerformed

    private void item9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item9ActionPerformed

    /**
     * Calls the setMenu() method to submit the chosen menu 
     * 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setMenu();
        jLabel4.setText("Menu Submitted, please exit.");
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
    * Updates the prices to reflect the coupons that are chosen.
    */
    public void setCouponPrices(int x){
    
        if(coupons[x].getSelectedItem().toString().equalsIgnoreCase("no coupon"))
            setMenu[x].applyCoupon(setMenu[x].getPrice(), 0);
        else if(coupons[x].getSelectedItem().toString().equalsIgnoreCase("10% off"))
            setMenu[x].applyCoupon(setMenu[x].getPrice(), 0.1);  
        else if(coupons[x].getSelectedItem().toString().equalsIgnoreCase("20% off"))
            setMenu[x].applyCoupon(setMenu[x].getPrice(), 0.2);
        else if(coupons[x].getSelectedItem().toString().equalsIgnoreCase("50% off"))
            setMenu[x].applyCoupon(setMenu[x].getPrice(), 0.5);
    
    }
    
    
    
    /**
    * If a menu item is checked off, the item is added to the setMenu array
    * and the prices are updated to the prices with coupons.
    */
    public void setMenu(){
        count = 0;
        
        if(item1.isSelected()){
            setMenu[count] = nachos;
            setCouponPrices(count);
            count++;
        }
        if(item15.isSelected()){
            setMenu[count] = onionRings;
            setCouponPrices(count);
            count++;
        }
        if(item13.isSelected()){
            setMenu[count] = fries;
            setCouponPrices(count);
            count++;
        }
        if(item14.isSelected()){
            setMenu[count] = mozzSticks;
            setCouponPrices(count);
            count++;
        }
        if(item20.isSelected()){
            setMenu[count] = potatoSkins;
            setCouponPrices(count);
            count++;
        }
        if(item19.isSelected()){
            setMenu[count] = sliders;
            setCouponPrices(count);
            count++;
        }
        if(item16.isSelected()){
            setMenu[count] = chickenWings;
            setCouponPrices(count);
            count++;
        }
        if(item4.isSelected()){
            setMenu[count] = chickenTenders;
            setCouponPrices(count);
            count++;
        }
        if(item18.isSelected()){
            setMenu[count] = cheeseFries;
            setCouponPrices(count);
            count++;
        }
        if(item3.isSelected()){
            setMenu[count] = sideGardenSal;
            setCouponPrices(count);
            count++;
        }
        if(item5.isSelected()){
            setMenu[count] = sideCaesarSal;
            setCouponPrices(count);
            count++;
        }
        if(item2.isSelected()){
            setMenu[count] = chipsSalsa;
            setCouponPrices(count);
            count++;
        }
        if(item17.isSelected()){
            setMenu[count] = friedRavioli;
            setCouponPrices(count);
            count++;
        }
        if(item6.isSelected()){
            setMenu[count] = jalapenoPoppers;
            setCouponPrices(count);
            count++;
        }
        if(item7.isSelected()){
            setMenu[count] = calamari;
            setCouponPrices(count);
            count++;
        }
        if(item8.isSelected()){
            setMenu[count] = soupOfTheDay;
            setCouponPrices(count);
            count++;
        }
        if(item9.isSelected()){
            setMenu[count] = strawberryDaiquiri;
            setCouponPrices(count);
            count++;
        }
        if(item10.isSelected()){
            setMenu[count] = pinaColada;
            setCouponPrices(count);
            count++;
        }
        if(item11.isSelected()){
            setMenu[count] = whiteZin;
            setCouponPrices(count);
            count++;
        }
        if(item12.isSelected()){
            setMenu[count] = cabernet;
            setCouponPrices(count);
            count++;
        }
        if(item21.isSelected()){
            setMenu[count] = pinotGrigio;
            setCouponPrices(count);
            count++;
        }
        if(item22.isSelected()){
            setMenu[count] = margarita;
            setCouponPrices(count);
            count++;
        }
        if(item23.isSelected()){
            setMenu[count] = yuengling;
            setCouponPrices(count);
            count++;
        }
        if(item24.isSelected()){
            setMenu[count] = budLight;
            setCouponPrices(count);
            count++;
        }
        
        
    }
    
    /**
    * Instantiates the menu items
    */
    public void populateMenu(){
    
        nachos = new MenuItem("Nachos", 6.99);
        onionRings = new MenuItem("Onion Rings", 5.99);
        fries = new MenuItem("Fries", 2.99);
        mozzSticks = new MenuItem("Mozzarella Sticks", 2.99);
        potatoSkins = new MenuItem("Potato Skins", 6.99);
        sliders = new MenuItem("Sliders", 8.99);
        chickenWings = new MenuItem("Chicken Wings", 7.99);
        chickenTenders = new MenuItem("Chicken Tenders", 7.99);
        cheeseFries = new MenuItem("Cheese Fries", 4.99);
        sideGardenSal = new MenuItem("Side Garden Salad", 3.99);
        sideCaesarSal = new MenuItem("Side Caesar Salad", 5.99);
        chipsSalsa = new MenuItem("Chips and Salsa", 3.99);
        friedRavioli = new MenuItem("Fried Ravioli", 5.99);
        jalapenoPoppers = new MenuItem("Jalapeno Poppers", 6.99);
        calamari = new MenuItem("Calamari", 8.99);
        soupOfTheDay = new MenuItem("Soup of the Day", 3.99);
        strawberryDaiquiri = new MenuItem("Strawberry Daiquiri", 8.50);
        pinaColada = new MenuItem("Pina Colada", 8.50);
        whiteZin = new MenuItem("White Zinfandel", 6.00);
        cabernet = new MenuItem("Cabernet", 6.50);
        pinotGrigio = new MenuItem("Pinot Grigio", 6.00);
        margarita = new MenuItem("Margarita", 8.00);
        yuengling = new MenuItem("23 oz. Yuengling", 7.00);
        budLight = new MenuItem("23 oz. Bud Light", 6.00);
    
    }
    
    /**
    * sets the text in the text fields to the default prices of each menu item.
    */    
    public void setDefaultPrices(){
    
        price1.setText(df.format(nachos.getPrice()));
        price15.setText(df.format(onionRings.getPrice()));
        price13.setText(df.format(fries.getPrice()));
        price14.setText(df.format(mozzSticks.getPrice()));
        price20.setText(df.format(potatoSkins.getPrice()));
        price19.setText(df.format(sliders.getPrice()));
        price16.setText(df.format(chickenWings.getPrice()));
        price4.setText(df.format(chickenTenders.getPrice()));
        price18.setText(df.format(cheeseFries.getPrice()));
        price3.setText(df.format(sideGardenSal.getPrice()));
        price5.setText(df.format(sideCaesarSal.getPrice()));
        price2.setText(df.format(chipsSalsa.getPrice()));
        price17.setText(df.format(friedRavioli.getPrice()));
        price6.setText(df.format(jalapenoPoppers.getPrice()));
        price7.setText(df.format(calamari.getPrice()));
        price8.setText(df.format(soupOfTheDay.getPrice()));
        price9.setText(df.format(strawberryDaiquiri.getPrice()));
        price10.setText(df.format(pinaColada.getPrice()));
        price11.setText(df.format(whiteZin.getPrice()));
        price12.setText(df.format(cabernet.getPrice()));
        price21.setText(df.format(pinotGrigio.getPrice()));
        price22.setText(df.format(margarita.getPrice()));
        price23.setText(df.format(yuengling.getPrice()));
        price24.setText(df.format(budLight.getPrice()));
        
    }
    
    /**
    * Sets the text in the check boxes to the names of each menu item and
    * checks every box off.
    */
    public void setCheckBoxes(){
    
        item1.setText(nachos.getName());
        item1.setSelected(true);
        item15.setText(onionRings.getName());
        item15.setSelected(true);
        item13.setText(fries.getName());
        item13.setSelected(true);
        item14.setText(mozzSticks.getName());
        item14.setSelected(true);
        item20.setText(potatoSkins.getName());
        item20.setSelected(true);
        item19.setText(sliders.getName());
        item19.setSelected(true);
        item16.setText(chickenWings.getName());
        item16.setSelected(true);
        item4.setText(chickenTenders.getName());
        item4.setSelected(true);
        item18.setText(cheeseFries.getName());
        item18.setSelected(true);
        item3.setText(sideGardenSal.getName());
        item3.setSelected(true);
        item5.setText(sideCaesarSal.getName());
        item5.setSelected(true);
        item2.setText(chipsSalsa.getName());
        item2.setSelected(true);
        item17.setText(friedRavioli.getName());
        item17.setSelected(true);
        item6.setText(jalapenoPoppers.getName());
        item6.setSelected(true);
        item7.setText(calamari.getName());
        item7.setSelected(true);
        item8.setText(soupOfTheDay.getName());
        item8.setSelected(true);
        item9.setText(strawberryDaiquiri.getName());
        item9.setSelected(true);
        item10.setText(pinaColada.getName());
        item10.setSelected(true);
        item11.setText(whiteZin.getName());
        item11.setSelected(true);
        item12.setText(cabernet.getName());
        item12.setSelected(true);
        item21.setText(pinotGrigio.getName());
        item21.setSelected(true);
        item22.setText(margarita.getName());
        item22.setSelected(true);
        item23.setText(yuengling.getName());
        item23.setSelected(true);
        item24.setText(budLight.getName());
        item24.setSelected(true);
    
    }
    
    /**
    * Loads combo boxes into an array to make code more compact in other methods
    */
    public void makeComboArray(){
    
        coupons[0] = coupon1;
        coupons[1] = coupon2;
        coupons[2] = coupon3;
        coupons[3] = coupon4;
        coupons[4] = coupon5;
        coupons[5] = coupon6;
        coupons[6] = coupon7;
        coupons[7] = coupon8;
        coupons[8] = coupon9;
        coupons[9] = coupon10;
        coupons[10] = coupon11;
        coupons[11] = coupon12;
        coupons[12] = coupon13;
        coupons[13] = coupon14;
        coupons[14] = coupon15;
        coupons[15] = coupon16;
        coupons[16] = coupon17;
        coupons[17] = coupon18;
        coupons[18] = coupon19;
        coupons[19] = coupon20;
        coupons[20] = coupon21;
        coupons[21] = coupon22;
        coupons[22] = coupon23;
        coupons[23] = coupon24;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPrices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox coupon1;
    private javax.swing.JComboBox coupon10;
    private javax.swing.JComboBox coupon11;
    private javax.swing.JComboBox coupon12;
    private javax.swing.JComboBox coupon13;
    private javax.swing.JComboBox coupon14;
    private javax.swing.JComboBox coupon15;
    private javax.swing.JComboBox coupon16;
    private javax.swing.JComboBox coupon17;
    private javax.swing.JComboBox coupon18;
    private javax.swing.JComboBox coupon19;
    private javax.swing.JComboBox coupon2;
    private javax.swing.JComboBox coupon20;
    private javax.swing.JComboBox coupon21;
    private javax.swing.JComboBox coupon22;
    private javax.swing.JComboBox coupon23;
    private javax.swing.JComboBox coupon24;
    private javax.swing.JComboBox coupon3;
    private javax.swing.JComboBox coupon4;
    private javax.swing.JComboBox coupon5;
    private javax.swing.JComboBox coupon6;
    private javax.swing.JComboBox coupon7;
    private javax.swing.JComboBox coupon8;
    private javax.swing.JComboBox coupon9;
    private javax.swing.JCheckBox item1;
    private javax.swing.JCheckBox item10;
    private javax.swing.JCheckBox item11;
    private javax.swing.JCheckBox item12;
    private javax.swing.JCheckBox item13;
    private javax.swing.JCheckBox item14;
    private javax.swing.JCheckBox item15;
    private javax.swing.JCheckBox item16;
    private javax.swing.JCheckBox item17;
    private javax.swing.JCheckBox item18;
    private javax.swing.JCheckBox item19;
    private javax.swing.JCheckBox item2;
    private javax.swing.JCheckBox item20;
    private javax.swing.JCheckBox item21;
    private javax.swing.JCheckBox item22;
    private javax.swing.JCheckBox item23;
    private javax.swing.JCheckBox item24;
    private javax.swing.JCheckBox item3;
    private javax.swing.JCheckBox item4;
    private javax.swing.JCheckBox item5;
    private javax.swing.JCheckBox item6;
    private javax.swing.JCheckBox item7;
    private javax.swing.JCheckBox item8;
    private javax.swing.JCheckBox item9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField price10;
    private javax.swing.JTextField price11;
    private javax.swing.JTextField price12;
    private javax.swing.JTextField price13;
    private javax.swing.JTextField price14;
    private javax.swing.JTextField price15;
    private javax.swing.JTextField price16;
    private javax.swing.JTextField price17;
    private javax.swing.JTextField price18;
    private javax.swing.JTextField price19;
    private javax.swing.JTextField price2;
    private javax.swing.JTextField price20;
    private javax.swing.JTextField price21;
    private javax.swing.JTextField price22;
    private javax.swing.JTextField price23;
    private javax.swing.JTextField price24;
    private javax.swing.JTextField price3;
    private javax.swing.JTextField price4;
    private javax.swing.JTextField price5;
    private javax.swing.JTextField price6;
    private javax.swing.JTextField price7;
    private javax.swing.JTextField price8;
    private javax.swing.JTextField price9;
    // End of variables declaration//GEN-END:variables
}
